### ISSUE TITLE
lui vao khong dung cho

### ISSUE THREAD

**Issue by tinh251993** [VUHAILAM/asio-multithreads-generate-number#1]
https://github.com/VUHAILAM/asio-multithreads-generate-number/blob/1b8e2b5438c3a174a4b184e53c7d5c471a9d7ed2/Generator.hpp#L16

**Comment by VUHAILAM** [comment]
không hiểu sao nó bị vậy nữa @@

**Comment by manhnt9** [comment]
Vào VS code chuyển hết tab thành space, có tính năng đó.
